version: "3.8"

services:
  mssqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: riverbook_sql_server
    ports:
      - "1433:1433"
    volumes:
      - sqlvolume:/var/opt/mssql
    environment:
      SA_PASSWORD: "reallyStrongPwd123"
      ACCEPT_EULA: "Y"

  redis:
    image: redis
    container_name: riverbook_redis
    restart: unless-stopped
    ports:
      - 6379:6379
    volumes: 
      - redis:/data

  papercut:
    image: jijiechen/papercut:latest
    container_name: papercut
    ports:
      - "25:25"
      - "37408:37408"

volumes:
  sqlvolume:
  redis: