@RiverBooksWebHost=https://localhost:7219

@BookId=28f9de3e-7584-4355-8b4e-cf301c159d30

GET {{RiverBooksWebHost}}/books/
Accept: application/json

###


GET {{RiverBooksWebHost}}/books/{{BookId}}
Accept: application/json

###

POST {{RiverBooksWebHost}}/books
Accept: application/json
Content-Type: application/json

{
    "id": "ede24de1-23d1-4be2-99fd-c5d94ff9e161",
    "title": "Modular Monoliths - Getting Started",
    "author": "Steve Smith",
    "price": 29.99
}

###

DELETE  {{RiverBooksWebHost}}/books/{{BookId}}
Accept: application/json

###

POST {{RiverBooksWebHost}}/books/{{BookId}}/priceHistory
Accept: application/json
Content-Type: application/json

{
    "id": "ede24de1-23d1-4be2-99fd-c5d94ff9e161",
    "newPrice": -9.99
}

###

POST {{RiverBooksWebHost}}/users
Accept: application/json
Content-Type: application/json

{
    "email": "sonpham@gmail.com",
    "password": "Pass@word1"
}

###

POST {{RiverBooksWebHost}}/users/login
Accept: application/json
Content-Type: application/json

{
    "email": "sonpham@gmail.com",
    "password": "Pass@word1"
}

###

@token=eyJhbGciOiJodHRwOi8vd3d3LnczLm9yZy8yMDAxLzA0L3htbGRzaWctbW9yZSNobWFjLXNoYTI1NiIsInR5cCI6IkpXVCJ9.eyJFbWFpbEFkZHJlc3MiOiJzb25waGFtQGdtYWlsLmNvbSIsImlhdCI6MTcwODc4MTMyNywiZXhwIjoxNzA4Nzg0OTI3LCJuYmYiOjE3MDg3ODEzMjd9.yKs3_qv1oPQNUr82sOu6FFCBsJplFk9DjkjspH5D0sE

# Add item to cart
POST {{RiverBooksWebHost}}/cart
Accept: text/plain
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "bookId": "28f9de3e-7584-4355-8b4e-cf301c159d30",
    "quantity": 1
}

###

# List items in cart
GET {{RiverBooksWebHost}}/cart
Accept: application/json
Authorization: Bearer {{token}}
Content-Type: application/json

###

# List All Orders
GET {{RiverBooksWebHost}}/orders
Accept: application/json
Authorization: Bearer {{token}}
Content-Type: application/json

###

# Checkout Cart
POST {{RiverBooksWebHost}}/cart/checkout
Accept: application/json
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "shippingAddressId": "28f9de3e-7584-4355-8b4e-cf301c159d30",
    "billingAddressId": "28f9de3e-7584-4355-8b4e-cf301c159d30"
}