@RiverBooksWebHost=https://localhost:7219

@BookId=ede24de1-23d1-4be2-99fd-c5d94ff9e161

GET {{RiverBooksWebHost}}/books/
Accept: application/json

###


GET {{RiverBooksWebHost}}/books/{{BookId}}
Accept: application/json

###

POST {{RiverBooksWebHost}}/books
Accept: application/json
Content-Type: application/json

{
    "id": "ede24de1-23d1-4be2-99fd-c5d94ff9e161",
    "title": "Modular Monoliths - Getting Started",
    "author": "Steve Smith",
    "price": 29.99
}

###

DELETE  {{RiverBooksWebHost}}/books/{{BookId}}
Accept: application/json

###

POST {{RiverBooksWebHost}}/books/{{BookId}}/priceHistory
Accept: application/json
Content-Type: application/json

{
    "id": "ede24de1-23d1-4be2-99fd-c5d94ff9e161",
    "newPrice": -9.99
}

###

POST {{RiverBooksWebHost}}/users
Accept: application/json
Content-Type: application/json

{
    "email": "sonpham@gmail.com",
    "password": "Pass@word1"
}

###

POST {{RiverBooksWebHost}}/users/login
Accept: application/json
Content-Type: application/json

{
    "email": "sonpham@gmail.com",
    "password": "Pass@word1"
}

###

@token=eyJhbGciOiJodHRwOi8vd3d3LnczLm9yZy8yMDAxLzA0L3htbGRzaWctbW9yZSNobWFjLXNoYTI1NiIsInR5cCI6IkpXVCJ9.eyJFbWFpbEFkZHJlc3MiOiJzb25waGFtQGdtYWlsLmNvbSIsImlhdCI6MTcwNzc4OTcyOCwiZXhwIjoxNzA3NzkzMzI4LCJuYmYiOjE3MDc3ODk3Mjh9.tUl_CRxH9L3VaNYSLUEDJ3fcs_cL1-GdmERXy496dQs

# Add item to cart
POST {{RiverBooksWebHost}}/cart
Accept: text/plain
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "bookId": "ede24de1-23d1-4be2-99fd-c5d94ff9e161",
    "quantity": 1
}

###

# List items in cart
GET {{RiverBooksWebHost}}/cart
Accept: application/json
Authorization: Bearer {{token}}
Content-Type: application/json