@RiverBooksWebHost=https://localhost:7219

@BookId=28f9de3e-7584-4355-8b4e-cf301c159d30

GET {{RiverBooksWebHost}}/books/
Accept: application/json

###


GET {{RiverBooksWebHost}}/books/{{BookId}}
Accept: application/json

###

POST {{RiverBooksWebHost}}/books
Accept: application/json
Content-Type: application/json

{
    "id": "ede24de1-23d1-4be2-99fd-c5d94ff9e161",
    "title": "Modular Monoliths - Getting Started",
    "author": "Steve Smith",
    "price": 29.99
}

###

DELETE  {{RiverBooksWebHost}}/books/{{BookId}}
Accept: application/json

###

POST {{RiverBooksWebHost}}/books/{{BookId}}/priceHistory
Accept: application/json
Content-Type: application/json

{
    "id": "ede24de1-23d1-4be2-99fd-c5d94ff9e161",
    "newPrice": -9.99
}

###

POST {{RiverBooksWebHost}}/users
Accept: application/json
Content-Type: application/json

{
    "email": "sonpham@gmail.com",
    "password": "Pass@word1"
}

###

POST {{RiverBooksWebHost}}/users/login
Accept: application/json
Content-Type: application/json

{
    "email": "sonpham@gmail.com",
    "password": "Pass@word1"
}

###

@token=eyJhbGciOiJodHRwOi8vd3d3LnczLm9yZy8yMDAxLzA0L3htbGRzaWctbW9yZSNobWFjLXNoYTI1NiIsInR5cCI6IkpXVCJ9.eyJFbWFpbEFkZHJlc3MiOiJzb25waGFtQGdtYWlsLmNvbSIsImlhdCI6MTcwODkwNTkyNywiZXhwIjoxNzA4OTA5NTI3LCJuYmYiOjE3MDg5MDU5Mjd9.YKp35yJZwfHEL5rd7VH4V-9dcTV0tzzchB7mEKWPxZE

# Add item to cart
POST {{RiverBooksWebHost}}/cart
Accept: text/plain
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "bookId": "28f9de3e-7584-4355-8b4e-cf301c159d30",
    "quantity": 1
}

###

# List items in cart
GET {{RiverBooksWebHost}}/cart
Accept: application/json
Authorization: Bearer {{token}}
Content-Type: application/json

###

# List All Orders
GET {{RiverBooksWebHost}}/orders
Accept: application/json
Authorization: Bearer {{token}}
Content-Type: application/json

###

# Checkout Cart
POST {{RiverBooksWebHost}}/cart/checkout
Accept: application/json
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "shippingAddressId": "8abae825-6f78-41b6-aa7f-a8ee2f7b9b6a",
    "billingAddressId": "8abae825-6f78-41b6-aa7f-a8ee2f7b9b6a"
}

###

# List Address
GET {{RiverBooksWebHost}}/users/addresses
Accept: application/json
Authorization: Bearer {{token}}
Content-Type: application/json

###

# Add Address to User
POST {{RiverBooksWebHost}}/users/addresses
Accept: application/json
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "street1": "3 Main St.",
  "street2": "Number 722",
  "city":"Anytown",
  "state":"OH",
  "postalCode":"12345-6789",
  "country":"USA"
}

###

# Flush cache
POST {{RiverBooksWebHost}}/flushcache
Accept: application/json
Content-Type: application/json

{
}